name: Build

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Build uberjar
      run: lein uberjar
    - name: Login to ECR
      id: ecr
      uses: elgohr/ecr-login-action@master
      with:
        access_key: ${{ secrets.AWS_ACCESS_KEY }}
        secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        region: eu-central-1
    - name: Publish Docker
      uses: elgohr/Publish-Docker-Github-Action@2.11
      with:
        username: ${{ steps.ecr.outputs.username }}
        password: ${{ steps.ecr.outputs.password }}
        registry: ${{ steps.ecr.outputs.registry }}
        name: vr-telegram-bot
        buildargs: TELEGRAM_TOKEN=${{ secrets.TELEGRAM_TOKEN }}
    
